"""
Mapa centralizado de equipos del Mundial 2026.
Usado por generador.py y actualizar_clasificados.py
"""

# Traducción: nombre en la API (inglés) → nombre en nuestro calendario (español)
EQUIPOS_MAP = {
    "Mexico": "México",
    "South Africa": "Sudáfrica",
    "Canada": "Canadá",
    "Bosnia And Herzegovina": "Bosnia y Herzegovina",
    "Bosnia & Herzegovina": "Bosnia y Herzegovina",
    "Bosnia": "Bosnia y Herzegovina",
    "Spain": "España",
    "Germany": "Alemania",
    "Netherlands": "Países Bajos",
    "United States": "EE.UU.",
    "USA": "EE.UU.",
    "South Korea": "Corea del Sur",
    "Korea Republic": "Corea del Sur",
    "Czech Republic": "Chequia",
    "Czechia": "Chequia",
    "Switzerland": "Suiza",
    "Morocco": "Marruecos",
    "Japan": "Japón",
    "Ecuador": "Ecuador",
    "England": "Inglaterra",
    "France": "Francia",
    "Portugal": "Portugal",
    "Haiti": "Haití",
    "New Zealand": "Nueva Zelanda",
    "Qatar": "Qatar",
    "Brazil": "Brasil",
    "Scotland": "Escocia",
    "Australia": "Australia",
    "Turkey": "Turquía",
    "Paraguay": "Paraguay",
    "Curacao": "Curazao",
    "Ivory Coast": "Costa de Marfil",
    "Cote D'Ivoire": "Costa de Marfil",
    "Sweden": "Suecia",
    "Tunisia": "Túnez",
    "Belgium": "Bélgica",
    "Egypt": "Egipto",
    "Cape Verde": "Cabo Verde",
    "Cabo Verde": "Cabo Verde",
    "Iran": "Irán",
    "Saudi Arabia": "Arabia Saudita",
    "Uruguay": "Uruguay",
    "Argentina": "Argentina",
    "Algeria": "Argelia",
    "Austria": "Austria",
    "Jordan": "Jordania",
    "Senegal": "Senegal",
    "Iraq": "Irak",
    "Norway": "Noruega",
    "Colombia": "Colombia",
    "DR Congo": "RD Congo",
    "Congo DR": "RD Congo",
    "Uzbekistan": "Uzbekistán",
    "Croatia": "Croacia",
    "Ghana": "Ghana",
    "Panama": "Panamá",
    "Barracas Central": "CA Barracas Central",
    "Huracan": "Huracán",
    "El Salvador": "El Salvador"
}

# Mapa de nombre en español → emoji de bandera
BANDERAS_MAP = {
    "México": "🇲🇽",
    "Sudáfrica": "🇿🇦",
    "Canadá": "🇨🇦",
    "Bosnia y Herzegovina": "🇧🇦",
    "España": "🇪🇸",
    "Alemania": "🇩🇪",
    "Países Bajos": "🇳🇱",
    "EE.UU.": "🇺🇸",
    "Corea del Sur": "🇰🇷",
    "Chequia": "🇨🇿",
    "Suiza": "🇨🇭",
    "Marruecos": "🇲🇦",
    "Japón": "🇯🇵",
    "Ecuador": "🇪🇨",
    "Inglaterra": "🏴\U000E0067\U000E0062\U000E0065\U000E006E\U000E0067\U000E007F",
    "Francia": "🇫🇷",
    "Portugal": "🇵🇹",
    "Haití": "🇭🇹",
    "Nueva Zelanda": "🇳🇿",
    "Qatar": "🇶🇦",
    "Brasil": "🇧🇷",
    "Escocia": "🏴\U000E0067\U000E0062\U000E0073\U000E0063\U000E0074\U000E007F",
    "Australia": "🇦🇺",
    "Turquía": "🇹🇷",
    "Paraguay": "🇵🇾",
    "Curazao": "🇨🇼",
    "Costa de Marfil": "🇨🇮",
    "Suecia": "🇸🇪",
    "Túnez": "🇹🇳",
    "Bélgica": "🇧🇪",
    "Egipto": "🇪🇬",
    "Cabo Verde": "🇨🇻",
    "Irán": "🇮🇷",
    "Arabia Saudita": "🇸🇦",
    "Uruguay": "🇺🇾",
    "Argentina": "🇦🇷",
    "Argelia": "🇩🇿",
    "Austria": "🇦🇹",
    "Jordania": "🇯🇴",
    "Senegal": "🇸🇳",
    "Irak": "🇮🇶",
    "Noruega": "🇳🇴",
    "Colombia": "🇨🇴",
    "RD Congo": "🇨🇩",
    "Uzbekistán": "🇺🇿",
    "Croacia": "🇭🇷",
    "Ghana": "🇬🇭",
    "Panamá": "🇵🇦",
    "El Salvador": "🇸🇻"
}

def normalize_name(name):
    """Convierte el nombre de la API al nombre en español del calendario."""
    return EQUIPOS_MAP.get(name, name)

def get_bandera(nombre_espanol):
    """Devuelve el emoji de bandera para un equipo."""
    return BANDERAS_MAP.get(nombre_espanol, "🏳️")
