"""
Mapa centralizado de equipos del Mundial 2026.
Usado por generador.py y actualizar_clasificados.py
"""

# Traducción: nombre en la API (inglés) → nombre en nuestro calendario (español)
EQUIPOS_MAP = {
    "Mexico": "México",
    "South Africa": "Sudáfrica",
    "Canada": "Canadá",
    "Bosnia And Herzegovina": "Bosnia y Herzegovina",
    "Bosnia & Herzegovina": "Bosnia y Herzegovina",
    "Bosnia-Herzegovina": "Bosnia y Herzegovina",
    "Bosnia": "Bosnia y Herzegovina",
    "Spain": "España",
    "Germany": "Alemania",
    "Netherlands": "Países Bajos",
    "United States": "EE.UU.",
    "USA": "EE.UU.",
    "South Korea": "Corea del Sur",
    "Korea Republic": "Corea del Sur",
    "Czech Republic": "Chequia",
    "Czechia": "Chequia",
    "Switzerland": "Suiza",
    "Morocco": "Marruecos",
    "Japan": "Japón",
    "Ecuador": "Ecuador",
    "England": "Inglaterra",
    "France": "Francia",
    "Portugal": "Portugal",
    "Haiti": "Haití",
    "New Zealand": "Nueva Zelanda",
    "Qatar": "Qatar",
    "Brazil": "Brasil",
    "Scotland": "Escocia",
    "Australia": "Australia",
    "Turkey": "Turquía",
    "Paraguay": "Paraguay",
    "Curacao": "Curazao",
    "Curaçao": "Curazao",
    "Ivory Coast": "Costa de Marfil",
    "Cote D'Ivoire": "Costa de Marfil",
    "Sweden": "Suecia",
    "Tunisia": "Túnez",
    "Belgium": "Bélgica",
    "Egypt": "Egipto",
    "Cape Verde": "Cabo Verde",
    "Cabo Verde": "Cabo Verde",
    "Cape Verde Islands": "Cabo Verde",
    "Iran": "Irán",
    "IR Iran": "Irán",
    "Iran (Islamic Republic of)": "Irán",
    "Saudi Arabia": "Arabia Saudita",
    "Uruguay": "Uruguay",
    "Argentina": "Argentina",
    "Algeria": "Argelia",
    "Austria": "Austria",
    "Jordan": "Jordania",
    "Senegal": "Senegal",
    "Iraq": "Irak",
    "Norway": "Noruega",
    "Colombia": "Colombia",
    "DR Congo": "RD Congo",
    "Congo DR": "RD Congo",
    "Uzbekistan": "Uzbekistán",
    "Croatia": "Croacia",
    "Ghana": "Ghana",
    "Panama": "Panamá",
    "Barracas Central": "CA Barracas Central",
    "Huracan": "Huracán",
    "El Salvador": "El Salvador",
    "Italy": "Italia",
    "Cameroon": "Camerún"
}

# Mapa de nombre en español → emoji de bandera
BANDERAS_MAP = {
    "México": "🇲🇽",
    "Sudáfrica": "🇿🇦",
    "Canadá": "🇨🇦",
    "Bosnia y Herzegovina": "🇧🇦",
    "España": "🇪🇸",
    "Alemania": "🇩🇪",
    "Países Bajos": "🇳🇱",
    "EE.UU.": "🇺🇸",
    "Corea del Sur": "🇰🇷",
    "Chequia": "🇨🇿",
    "Suiza": "🇨🇭",
    "Marruecos": "🇲🇦",
    "Japón": "🇯🇵",
    "Ecuador": "🇪🇨",
    "Inglaterra": "🏴\U000E0067\U000E0062\U000E0065\U000E006E\U000E0067\U000E007F",
    "Francia": "🇫🇷",
    "Portugal": "🇵🇹",
    "Haití": "🇭🇹",
    "Nueva Zelanda": "🇳🇿",
    "Qatar": "🇶🇦",
    "Brasil": "🇧🇷",
    "Escocia": "🏴\U000E0067\U000E0062\U000E0073\U000E0063\U000E0074\U000E007F",
    "Australia": "🇦🇺",
    "Turquía": "🇹🇷",
    "Paraguay": "🇵🇾",
    "Curazao": "🇨🇼",
    "Costa de Marfil": "🇨🇮",
    "Suecia": "🇸🇪",
    "Túnez": "🇹🇳",
    "Bélgica": "🇧🇪",
    "Egipto": "🇪🇬",
    "Cabo Verde": "🇨🇻",
    "Irán": "🇮🇷",
    "Arabia Saudita": "🇸🇦",
    "Uruguay": "🇺🇾",
    "Argentina": "🇦🇷",
    "Argelia": "🇩🇿",
    "Austria": "🇦🇹",
    "Jordania": "🇯🇴",
    "Senegal": "🇸🇳",
    "Irak": "🇮🇶",
    "Noruega": "🇳🇴",
    "Colombia": "🇨🇴",
    "RD Congo": "🇨🇩",
    "Uzbekistán": "🇺🇿",
    "Croacia": "🇭🇷",
    "Ghana": "🇬🇭",
    "Panamá": "🇵🇦",
    "El Salvador": "🇸🇻",
    "Italia": "🇮🇹",
    "Camerún": "🇨🇲"
}

# Mapa auxiliar en minúsculas para búsqueda insensible a mayúsculas/minúsculas
# (la API a veces devuelve "Bosnia and Herzegovina" con 'and' en minúscula, etc.)
_EQUIPOS_MAP_LOWER = {clave.lower(): valor for clave, valor in EQUIPOS_MAP.items()}

def normalize_name(name):
    """Convierte el nombre de la API al nombre en español del calendario."""
    if name in EQUIPOS_MAP:
        return EQUIPOS_MAP[name]
    # Fallback insensible a mayúsculas/minúsculas
    return _EQUIPOS_MAP_LOWER.get(name.lower(), name)

def get_bandera(nombre_espanol):
    """Devuelve el emoji de bandera para un equipo."""
    return BANDERAS_MAP.get(nombre_espanol, "🏳️")

# Mapa de nombre en español → código de 3 letras (para el bracket visual)
CODIGOS_MAP = {
    "México": "MEX",
    "Sudáfrica": "RSA",
    "Canadá": "CAN",
    "Bosnia y Herzegovina": "BIH",
    "España": "ESP",
    "Alemania": "GER",
    "Países Bajos": "NED",
    "EE.UU.": "USA",
    "Corea del Sur": "KOR",
    "Chequia": "CZE",
    "Suiza": "SUI",
    "Marruecos": "MAR",
    "Japón": "JPN",
    "Ecuador": "ECU",
    "Inglaterra": "ENG",
    "Francia": "FRA",
    "Portugal": "POR",
    "Haití": "HAI",
    "Nueva Zelanda": "NZL",
    "Qatar": "QAT",
    "Brasil": "BRA",
    "Escocia": "SCO",
    "Australia": "AUS",
    "Turquía": "TUR",
    "Paraguay": "PAR",
    "Curazao": "CUW",
    "Costa de Marfil": "CIV",
    "Suecia": "SWE",
    "Túnez": "TUN",
    "Bélgica": "BEL",
    "Egipto": "EGY",
    "Cabo Verde": "CPV",
    "Irán": "IRN",
    "Arabia Saudita": "KSA",
    "Uruguay": "URU",
    "Argentina": "ARG",
    "Argelia": "ALG",
    "Austria": "AUT",
    "Jordania": "JOR",
    "Senegal": "SEN",
    "Irak": "IRQ",
    "Noruega": "NOR",
    "Colombia": "COL",
    "RD Congo": "COD",
    "Uzbekistán": "UZB",
    "Croacia": "CRO",
    "Ghana": "GHA",
    "Panamá": "PAN",
    "El Salvador": "SLV",
    "Italia": "ITA",
    "Camerún": "CMR",
}

def get_codigo(nombre_espanol):
    """Devuelve el código de 3 letras para un equipo."""
    return CODIGOS_MAP.get(nombre_espanol, "TBD")
